### ISSUE TITLE
terminal version does not show version any more

### ISSUE THREAD

**Issue by Wimmelbach** [laurent22/joplin#15738]
### Operating system

Linux

### Joplin version

3.6.2

### Desktop version info

Joplin 3.6.2 terminal version

### Current behaviour

After updating Joplin from version 1.5.1 to 1.6.2 on my Rhaspberry Pi I have the following Issue:
When entering "joplin version" in the terminal I get:

Cannot find module '../package.json'
Require stack:
- /home/pi/.npm-global/lib/node_modules/joplin/command-version.js
- /home/pi/.npm-global/lib/node_modules/joplin/app.js
- /home/pi/.npm-global/lib/node_modules/joplin/main.js

### Expected behaviour

I expect to get the information of the installed version as I got it with all versions before.

### Logs

2026-06-22 13:29:12: Performance: BaseApplication/start: Start at 3.43s
2026-06-22 13:29:12: App: Profile directory: /home/pi/.config/joplin
2026-06-22 13:29:12: App: Root profile directory: /home/pi/.config/joplin
2026-06-22 13:29:12: Database was open successfully
2026-06-22 13:29:12: Checking for database schema update...
2026-06-22 13:29:12: Current database version {"version":49,"table_fields_version":49}
2026-06-22 13:29:12: Upgrading database from version 49
2026-06-22 13:29:12: New version: 49. Previously recorded version: 49
2026-06-22 13:29:12: KeychainService: checking if keychain supported
2026-06-22 13:29:12: KeychainService: check was already done - skipping. Supported: 0
2026-06-22 13:29:12: e2ee/utils: Master password is not set - trying to get it from the active master key...
2026-06-22 13:29:12: handleSyncStartupOperation: Processing operation: 0
2026-06-22 13:29:12: App: Client ID: 7da5be2c66b34b33bcdedc8447cc2991

**Comment by laurent22** [comment]
@personalizedrefrigerator, Claude points to commit cda4073bf which at first sight seems to make sense but I didn't look into it in details
